MOUSEKEY_ENABLE     = no      # Mouse keys
RGBLIGHT_ENABLE     = no      # Enable WS2812 RGB underlight.
VIA_ENABLE          = yes     # Enable VIA
VIAL_ENABLE         = yes     # Enable VIAL
OLED_ENABLE         = no
OLED_DRIVER         = SSD1306
EXTRAKEY_ENABLE     = yes
LTO_ENABLE          = no
QMK_SETTINGS        = yes
COMBO_ENABLE        = yes
KEY_OVERRIDE_ENABLE = no
TAP_DANCE_ENABLE = no
